export const setsCategory = {
  id: "1",
  slug: "sets",
  title: "ست",
  products: [
    {
      id: "101",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 200000,
      numberOfSales: 24,
      publishTime: "1404/01/20-18/40/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "102",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/01/20-11/10/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero03.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "103",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 21,
      publishTime: "1404/04/20-15/30/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero04.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "104",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 10,
      publishTime: "1404/01/25-11/30/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero06.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "105",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 27,
      publishTime: "1404/01/20-20/30/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero03.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "106",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/11/20-18/30/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "107",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/01/20-18/30/45",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "108",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/01/20-18/34/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "109",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/04/20-18/30/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "110",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/03/20-18/33/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero06.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    ,
    {
      id: "111",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/03/20-18/33/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero06.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    ,
    {
      id: "112",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      numberOfSales: 20,
      publishTime: "1404/03/20-18/33/05",
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero06.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
  ],
};
