export const setsCategory = {
  id: "1",
  slug: "sets",
  title: "ست",
  products: [
    {
      id: "101",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 200000,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "102",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "103",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "104",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "105",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "106",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "107",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "108",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "109",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero05.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
    {
      id: "110",
      slug: "jeans-slim-fit",
      name: "شلوار جین اسلیم فیت",
      price: 320000,
      discountePercentage: 20,
      discountedPrice: 0,
      colors: ["آبی", "مشکی"],
      sizes: ["S", "M", "L", "XL"],
      images: ["/images/hero06.jpg", "/images/hero06.jpg"],
      rating: 4.8,
      description: "شلوار جین اسلیم فیت با الیاف باکیفیت",
    },
  ],
};
